export const SCREENS = {
  SPLASH_SCREEN: 'SplashScreen',
  HOME_SCREEN: 'HomeController',
  ROOTDRAWER: 'RootDrawer',
  EVENTS_SCREEN: 'Events',
  NEWS_SCREEN: 'NewsController',
  GALLERY_SCREEN: 'GalleryController',
  PRAY_REQUEST: 'PrayReqController',
  OUR_CHURCH: 'OurChurchController',
  CONTACT_SCREEN: 'ContactController',
  WOMENS_FEST: 'WomensFestival',
  HEMA_JOHN: 'HemaJohn',
  BHAJAN_SERMON: 'BhajanSermon',
  ASANAM_2023: 'Asanam2023',
  DIAMOND_JUBILEE: 'DiamondJubilee',
  VBS_2023: 'VBS2023',
  XMAS_2018: 'Xmas2018',
  XMAS_2012: 'Xmas2012',
  HILL_PEOPLE: 'HillPeople',
  SILVER_JUBILEE: 'SilverJubilee',
  DIAMONDJUBI_NEWS: 'DiamondJubileeNews',
  HEMA_JOHN_NEWS: 'HemaJohnConcert',
  WOMENS_FEST_NEWS: 'WomensFestNews',
};
